const actionTypes = {
    PRODUCT_GET_ALL_PRODUCT: "PRODUCT_GET_ALL_PRODUCT",
    PRODUCT_GET_ALL_PRODUCT_SUCCEED: "PRODUCT_GET_ALL_PRODUCT_SUCCEED",
    PRODUCT_GET_ALL_PRODUCT_FAILED: "PRODUCT_GET_ALL_PRODUCT_FAILED",
};

export default actionTypes;
