const actionTypes = {
    // PRODUCT
    PRODUCT_GET_ALL_PRODUCT: "PRODUCT_GET_ALL_PRODUCT",
    PRODUCT_GET_ALL_PRODUCT_SUCCEED: "PRODUCT_GET_ALL_PRODUCT_SUCCEED",
    PRODUCT_GET_ALL_PRODUCT_FAILED: "PRODUCT_GET_ALL_PRODUCT_FAILED",

    // PRODUCT TYPE
    PRODUCT_GET_ALL_PRODUCT_TYPE: "PRODUCT_GET_ALL_PRODUCT_TYPE",
    PRODUCT_GET_ALL_PRODUCT_TYPE_SUCCEED: "PRODUCT_GET_ALL_PRODUCT_TYPE_SUCCEED",
    PRODUCT_GET_ALL_PRODUCT_TYPE_FAILED: "PRODUCT_GET_ALL_PRODUCT_TYPE_FAILED",
    PRODUCT_CREATE_PRODUCT_TYPE: "PRODUCT_CREATE_PRODUCT_TYPE",
    PRODUCT_CREATE_PRODUCT_TYPE_SUCCEED: "PRODUCT_CREATE_PRODUCT_TYPE_SUCCEED",
    PRODUCT_CREATE_PRODUCT_TYPE_FAILED: "PRODUCT_CREATE_PRODUCT_TYPE_FAILED",
    PRODUCT_UPDATE_PRODUCT_TYPE: "PRODUCT_UPDATE_PRODUCT_TYPE",
    PRODUCT_UPDATE_PRODUCT_TYPE_SUCCEED: "PRODUCT_UPDATE_PRODUCT_TYPE_SUCCEED",
    PRODUCT_UPDATE_PRODUCT_TYPE_FAILED: "PRODUCT_UPDATE_PRODUCT_TYPE_FAILED",
    PRODUCT_DELETE_PRODUCT_TYPE: "PRODUCT_DELETE_PRODUCT_TYPE",
    PRODUCT_DELETE_PRODUCT_TYPE_SUCCEED: "PRODUCT_DELETE_PRODUCT_TYPE_SUCCEED",
    PRODUCT_DELETE_PRODUCT_TYPE_FAILED: "PRODUCT_DELETE_PRODUCT_TYPE_FAILED",
    
    // MANUFACTURER
    MANUFACTURER_GET_ALL_MANUFACTURER: "MANUFACTURER_GET_ALL_MANUFACTURER",
    MANUFACTURER_GET_ALL_MANUFACTURER_SUCCEED: "MANUFACTURER_GET_ALL_MANUFACTURER_SUCCEED",
    MANUFACTURER_GET_ALL_MANUFACTURER_FAILED: "MANUFACTURER_GET_ALL_MANUFACTURER_FAILED",
    MANUFACTURER_CREATE_MANUFACTURER: "MANUFACTURER_CREATE_MANUFACTURER",
    MANUFACTURER_CREATE_MANUFACTURER_SUCCEED: "MANUFACTURER_CREATE_MANUFACTURER_SUCCEED",
    MANUFACTURER_CREATE_MANUFACTURER_FAILED: "MANUFACTURER_CREATE_MANUFACTURER_FAILED",
    MANUFACTURER_UPDATE_MANUFACTURER: "MANUFACTURER_UPDATE_MANUFACTURER",
    MANUFACTURER_UPDATE_MANUFACTURER_SUCCEED: "MANUFACTURER_UPDATE_MANUFACTURER_SUCCEED",
    MANUFACTURER_UPDATE_MANUFACTURER_FAILED: "MANUFACTURER_UPDATE_MANUFACTURER_FAILED",
    MANUFACTURER_DELETE_MANUFACTURER: "MANUFACTURER_DELETE_MANUFACTURER",
    MANUFACTURER_DELETE_MANUFACTURER_SUCCEED: "MANUFACTURER_DELETE_MANUFACTURER_SUCCEED",
    MANUFACTURER_DELETE_MANUFACTURER_FAILED: "MANUFACTURER_DELETE_MANUFACTURER_FAILED",

};

export default actionTypes;
